apiVersion: v1
kind: Service
metadata:
  name: httpshswf-network-service
spec:
  type: NodePort
  selector:
    app: httpshswf-network
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
